### ISSUE TITLE
plotly.plotly is deprecated

### ISSUE THREAD

**Issue by nickprock** [mjbahmani/10-steps-to-become-a-data-scientist#10]
Hi @mjbahmani ,

congratulations for the repo is very nice and useful.
At **The Data Scientist’s Toolbox Tutorial - 1** cell 3, you import the packages, plotly.plotly module is deprecated. Please use *chart_studio.plotly*.
Now I'm trying to complete the notebooks, if you want I can submit a pull request.

I look forward to updates.

**Comment by nickprock** [comment]
Another issue, you load and use for example a dataset about the house_price but the csv file in the folder *.../input/* is about titanic dataset I think.

**Comment by mjbahmani** [comment]
Hi @nickprock 
I would be more than happy if you could help to finish this repo! :)
