### ISSUE TITLE
Top 5 Data Visualization Libraries Tutorial 

### ISSUE THREAD

**Issue by TaichiLi** [mjbahmani/10-steps-to-become-a-data-scientist#6]
```
# import kernels and users to play with it (MJ Bahmani)
#command--> 1
users = pd.read_csv("../input/Users.csv")
kernels = pd.read_csv("../input/Kernels.csv")
messages = pd.read_csv("../input/ForumMessages.csv")
```
Where are the three csv files?

**Comment by mjbahmani** [comment]
You can download them in following URL:
https://www.kaggle.com/mjbahmani/top-5-data-visualization-libraries-tutorial

**Comment by pranimation** [comment]
could you check the link again @mjbahmani , I think dataset is not present there. BTW Your work is very helpful until now.
